{{- if .Values.backup_job.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-postgres-backup
  namespace: {{ .Release.Namespace }}
  {{- if .Values.backup_job.annotations.aws }}
  annotations:
    eks.amazonaws.com/role-arn: {{ toYaml .Values.backup_job.annotations.aws }}
  {{- end }}
{{- end }}
